feat: adding pod labels in webhooks
jenkins-x/lighthouse pull request #1489
Opened 2022-09-30 10:51 UTC by joker00777

Hi @ankitm123 we have a use case where we want to add some pod Labels : ). So it would be great if this can be done?

2022-10-04 20:29 UTC, msvticket commented
/ok-to-test

2022-10-04 20:32 UTC, msvticket commented on charts/lighthouse/values.yaml
> +  podLables: {}
```suggestion
  podLabels: {}
```

2022-10-04 20:35 UTC, msvticket requested changes
Please fix spelling of labels!

2022-10-04 20:35 UTC, msvticket commented on charts/lighthouse/templates/webhooks-deployment.yaml
> +{{- end }}
```suggestion
{{- if  .Values.webhooks.podLabels }}
{{ toYaml .Values.webhooks.podLabels | indent 8 }}
{{- end }}
```

2022-10-04 20:35 UTC, msvticket commented on charts/lighthouse/values.yaml
> +  podLables: {}
```suggestion
  podLabels: {}
```

2022-10-05 06:12 UTC, joker00777 commented
Done @msvticket : ).

2022-10-05 07:16 UTC, msvticket approved these changes

2022-10-05 07:25 UTC, merged