fix: prevent repo from stop being handled
jenkins-x/lighthouse pull request #1523
Opened 2023-03-10 12:02 UTC by msvticket

## Fix of errors

```
Error creating agent for PushEvent.: failed to create agent: failed to calculate in repo config: failed to load trigger config for repository jenkins-x/jx3-versions for ref : failed to switch to ref : failed to merge repository jenkins-x/jx3-versions: failed to run command in dir /var/tmp/gitrepo2428068395: git, [merge FETCH_HEAD]: Updating 3e21ade2..3bebed28 error: Your local changes to the following files would be overwritten by merge:
	src/get-selectors-and-clean.sh
Please commit your changes or stash them before you merge. Aborting: exit status 1
```

## Explanation
--no-checkout stages the deletion of all files which causes problem when merging upstreams changes to working directory. This is fixed by bypassing working directory when fetching upstreams changes to local branch no conflict occurs. Conflicts are then ignored during checking out with --force.

## Other fixes

Stop using deprecated diff.ObjectReflectDiff

Sparse checkout is not working in the latest release of lighthouse since it got a new version of git with a different default handling of sparse checkouts. This is also addressed in this PR.

Make event specific logging fields get logged again

Ignore push events for deletion of branches that would otherwise cause error messages

Wrap more errors go get context

2023-03-13 10:19 UTC, msvticket commented
/cc ankitm123 tomhobson babadofar

2023-03-22 16:08 UTC, tomhobson requested changes

2023-03-22 19:26 UTC, msvticket commented on pkg/git/v2/interactor.go
> +	if out, err := i.executor.Run(append([]string{"sparse-checkout", "set", "--no-cone"}, sparseCheckoutPatterns...)...); err != nil {
--no-cone

2023-03-23 08:28 UTC, tomhobson approved these changes

2023-03-23 08:28 UTC, tomhobson commented on pkg/git/v2/interactor.go
> +	if out, err := i.executor.Run(append([]string{"sparse-checkout", "set", "--no-cone"}, sparseCheckoutPatterns...)...); err != nil {
Cool

2023-03-23 08:30 UTC, merged